uwblueprint/paramedics-web

- .dockerignore
- Dockerfile
- package-lock.json
- package.json
- server.js
Follow [this](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/) tutorial to build node app with docker.
> Add dockerfile, package.json, scaffold express

- package-lock.json
- package.json
This commit supports hot reloading by using the Docker commands. Must rebuild image for this functionality.
> Updated package.json to support live-reloading via Nodemon

- Dockerfile
- docker-compose.yaml
- package.json
> Initial setup for containerizing code

- package-lock.json
- package.json
- server.js
installs:
apollo-server-express: graphql server
body-parser: reads requests
express: backend framework
Includes simple usage example callable from GraphiQL at `/graphiql`:
> Install backend modules

- resolvers/user.js
- schema/user.js
- server.js
Adds basic POST mutation for users.
Updated schema/resolver for users to allow for mutations
Manual testing on graphiql
> Add mutation for users

- build/builder/command_center.cc
>Brief description of high-level changes; link notion task and other relevant links
DESCRIPTION
>List of specific changes made; can also use inline comments in the diff if that makes more sense
- SPECIFIC_CHANGE
>Embed if they are helpful
>Describe any testing you did (e.g. manual testing) or test suites you added/changed
- NEW_TEST
> Fixing compilation errors on mac

- build/builder/command_center.cc
- docker-compose-dev.yaml
>Brief description of high-level changes; link notion task and other relevant links
DESCRIPTION
>List of specific changes made; can also use inline comments in the diff if that makes more sense
- SPECIFIC_CHANGE
>Embed if they are helpful
>Describe any testing you did (e.g. manual testing) or test suites you added/changed
- NEW_TEST
> Fixing build issues?

- docker-compose-prod.yaml
Runs nodemon on dev now
DESCRIPTION
fix name resolving issue in docker-compose
pls test for me
kudos to steven
> fix name resolving issue in docker-compose

- resolvers/user.js
- schema/user.js
Added update and deletion resolvers for user to complete CRUD for this table. 
[Notion task](https://www.notion.so/uwblueprintexecs/9224caeb21ce4350b8a1dc378d393323?v=43f44ac04d734394b7f7edc636c523b4&p=a96996ee761b4881afc5d669f5704562)
DESCRIPTION
- Added `updateUser` and `deleteUser` resolvers in `schema/user.js` and `resolvers/user.js`
Deleting non-existant user
Updating a subset of fields for a user if user is non-existent
Updating a subset of fields for a user if accessLevel not properly defined
Updating a subset of fields for a user if accessLevel properly defined
- Manual testing using GraphIQL
> CRUD for Users

- migrations/20200213004252-change-date-column-names.js
- models/event.js
- package-lock.json
- package.json
- resolvers/event.js
- schema/event.js
- seeders/20200129021755-events.js
Adding CRUD mutations to the events table.
Note:  Undo all migrations, then remigrate before running any code.
First:
`sequelize-cli db:migrate:undo:all`
Then: 
`sequelize-cli db:migrate`
[Notion task](https://www.notion.so/uwblueprintexecs/CRUD-operations-for-events-132c40bbac0a48918a374f170e9becf6)
* Add create, update, and delete mutations to the events table 
* Schema updated in `schema/event.js`
* Resolvers updated in `resolvers/event.js`
* Linked changes in `graphql.js`
* Implented create, update and deletion resolvers in `schema/event.js` and `resolvers/event.js`
* Note: The return type of resolvers is an object of the dataset itself. 
* Error handling for updates (suggesting that we make some error file to pull in common error outputs)
* Changed schema to reflect inbuilt Sequelize …
> CRUD mutations for event table

- graphql.js
>Brief description of high-level changes; link notion task and other relevant links
DESCRIPTION
Fixed the Query.collectionPoints error due to graphql.js unresolved conflicts
>List of specific changes made; can also use inline comments in the diff if that makes more sense
- Changed `graphql.js` typedefs of schema and resolvers to accurately reflect the current state
>Embed if they are helpful
>Describe any testing you did (e.g. manual testing) or test suites you added/changed
- Manual testing in graphql playground
> fixed Query.collectionPoints error

- seeders/20200206002553-demo-collectionPoint.js
fixing collection point seeder
Add field introduced in recent pr
manual testing
> Add eventDate to collection point seeder

- migrations/20200303023602-collectionPoints.js
- models/collectionPoint.js
- resolvers/collectionPoint.js
- resolvers/hospital.js
- schema/collectionPoint.js
- seeders/20200206002553-demo-collectionPoint.js
- seeders/20200206005427-demo-patient.js
>Brief description of high-level changes; link notion task and other relevant links
Added create, read, update, and delete operations
>List of specific changes made; can also use inline comments in the diff if that makes more sense
**Added:**
- `addCollectionPoint(name: String!, eventID: ID!)` to the resolver and schema
- `updateCollectionPoint(id: ID!, name: String, eventID: ID)` to the resolver and schema
- `deleteCollectionPoint(id: ID!)` to the resolver and schema
- `DateTime` instead of `Date` for createdAt and updatedAt
>Embed if they are helpful
**Events:**
**Adding Collection Point:**
**Updating Collection Point's eventID:**
**Updating Collection Point's …
> Added CRUD Operations for Collection Points

- migrations/20200705014540-extend-patient-statuses.js
- package-lock.json
- package.json
add delete patient status
[Notion task](https://www.notion.so/uwblueprintexecs/add-delete-patient-statuses-b3737d7a302c45a19446f6758f608325)
- add delete patient status
- no existing entries in your db should be affected
- if you haven't already, pull latest `paramedics-builder` changes and build new `builder` binary
- rebuild your backend container first (so the new node module is properly installed)
- this will run the new migration (as migrations run on every container start)
- shell into your db container - from your local paramedics-web, `../builder -e db`
- run `\dT+ enum_patients_status`
- check that the `DELETED` enum is there
---
- shell into your backend …
> add delete patient status

- package-lock.json
- package.json
adding ngrok to enable tunneling - see this notion doc for more context
https://www.notion.so/uwblueprintexecs/Tunneling-872fa180fce14d3b9c5cc35c17e5a49a
[Notion task](https://www.notion.so/uwblueprintexecs/tunneling-for-design-verification-79725a154988407ba51af2e745d0185d)
- add ngrok to `package.json`
- restart the container and test that ngrok works
- run `ngrok http 4000` inside the container
- on your browser, go to the ngrok link it gives you and verify that the graphql playground shows up
- also checkout this branch locally https://github.com/uwblueprint/paramedics-react/pull/14
- run tunnel start and verify that everything works as described in the notion doc
> add ngrok for tunneling

- migrations/20200713233601-add-hospital-column-to-patients.js
- models/patient.js
- resolvers/patient.js
- schema/patient.js
[Notion task](https://www.notion.so/uwblueprintexecs/CCP-Dashboard-Screen-2-f600fbc4a87442c4a23684da964823cd)
- Add patient/hospital association (`hospitalId` column in `patients` table)
- Update `addPatient` and `updatePatient` mutations to include `hospitalId`
1. Add a patient using `addPatient` with a valid `hospitalId`
2. Add a patient using `addPatient` with an invalid `hospitalId`
3. Update an existing patient using `updatePatient` with a valid `hospitalId`
4. Update an existing patient using `updatePatient` with an invalid `hospitalId`
> Add hospital and patient association

- migrations/20200719025533-add-name-column-users.js
- models/user.js
- resolvers/user.js
- schema/user.js
- seeders/20200128023056-demo-user.js
- seeders/20200129021755-events.js
- seeders/20200206002553-demo-collectionPoint.js
- seeders/20200206005427-demo-patient.js
- seeders/20200609004045-EventAmbulances.js
- seeders/20200609004052-EventHospitals.js
[Notion task](https://www.notion.so/uwblueprintexecs/users-name-schema-d08f5466736d4ac48d2dccbcc1e9e404)
- removed "firstName" and "lastName" fields from user type and created a single field "name"
- updated seeders 
- updates user schema, model, resolvers
- created new migration
- seeded data
- tested migration up and down functions
- tested resolvers
> users name schema

- graphql.js
- migrations/20200715014355-create-location-pins.js
- models/locationPins.js
- resolvers/locationPin.js
- schema/locationPin.js
- seeders/20200717011432-locationPins.js
[Notion task](https://www.notion.so/uwblueprintexecs/396370c5e09f4c28bc7f455a7e84c908?v=3751aa62a2594c74b7e0ecb363304c24&p=09b772f158924f9c8d4196a723e28a9a)
- Added table `locationPins` to store location-based information for pins added on maps
- Added resolvers (add, update, delete) and querying functionality
- Added seeders
- Steps:
- Run migration (should already be migrated if using new builder)
- Run seeder
- Go ham on GraphIQL
Multi-pin querying
Single-pin querying
Querying pins belonging to a particular event
Adding pin
Adding pin error - no associated event
Adding pin error - no latitude given (same error applies for longitude)
Updating pin
Updating pin error - no …
> Location Pins

- migrations/20200730000410-add-ambulance-column-patients.js
- models/patient.js
- resolvers/patient.js
- schema/patient.js
[Notion task](https://www.notion.so/uwblueprintexecs/Change-Status-Transport-flow-36737be85ca640709ad2109a5ca0ecd8)
> Changes
- Added ambulanceId to patient schema/models
- Updated patient mutations to include ambulanceId
- migration for adding ambulance column to patient table
- Tested addPatient/updatePatient/deletePatient
- Tested error handling for invalid ambulance IDs
> Adds ambulance association to patients

- resolvers/event.js
- resolvers/patient.js
- schema/event.js
[Related Notion task](https://www.notion.so/uwblueprintexecs/Event-Dashboard-Screen-af7c8340fc394304abc1cabaa5ae2296)
- Remove existing `addAmbulanceToEvent` and `addHospitalToEvent` (for single ambulance/hospital)
- Create the following new mutations to achieve our desired functionality on event dashboard i.e. include/exclude single and multiple ambulance(s)/hospital(s)
- `addAmbulancesToEvent`
- Add any number of ambulances (will not throw error if any have existing association)
- `addHospitalsToEvent`
- Add any number of hospitals (will not throw error if any have existing association)
- `deleteAmbulancesFromEvent`
- Delete any number of ambulances (will not throw error …
> Add mutations for adding/deleting hospital-event and ambulance-event associations

- resolvers/ambulance.js
- resolvers/hospital.js
- Preventing resource deletion if patient is associated
- GraphIQL testing:
- Delete hospital/ambulance and see it work (note how association with event is also deleted)
- Associate patient with hospital/ambulance and see it not work (note how association with event is not deleted)
> Blocking deletion of resource if patient is associated

- resolvers/event.js
- Update `addEvent` mutation to return event `id`
- Add an event using `addEvent` with `id` field
> Update addEvent to return id

- migrations/20200824194331-patient-gender.js
- schema/patient.js
- seeders/20200206005427-demo-patient.js
[Notion task](https://www.notion.so/uwblueprintexecs/4b97736541b2418eac9025b0efcf3c58?v=f07847298f194931a3f9052e205544e5&p=fd09d01ba3984ae6a9d07b9fa71c363b)
- Created migration that:
- Converts all prexisting "Male" and "Female" genders to "M" and "F" among patients
- Created an enum for gender with values of "M" and "F"
- Updated GraphQL schema to reflect gender enum
- Updated patient seeders to remove gender fields that were invalid (i.e. "unknown"). 
- Since there are seeding changes in this PR, make sure you undo all seeders and re-seed the database
- Migrated and un-migrated the enum several times
- For each of the migrations, I made sure that the database updated …
> Gender changes for patient

- resolvers/ambulance.js
- resolvers/collectionPoint.js
- resolvers/event.js
- resolvers/hospital.js
- resolvers/locationPin.js
- resolvers/patient.js
- resolvers/user.js
- schema/ambulance.js
- schema/collectionPoint.js
- schema/event.js
- schema/hospital.js
- schema/locationPin.js
- schema/patient.js
- schema/user.js
[Notion ticket](https://www.notion.so/uwblueprintexecs/delete-and-edit-mutation-cleanup-98ad81733016484b928909fb184e7360)
- Update following delete mutations to return the deleted ID
- ambulance
- CCP (collectionPoint)
- event
- hospital
- locationPin
- patient
- user
**Ambulance**
Delete Successfully
Delete Error
- Error deleting ambulance with associated patients
- Error deleting ambulance with invalid ID
**CCP**
Delete Successfully
Delete Error
- Invalid ID
**Event**
Delete Successfully
Delete Error
- Invalid ID
**Hospital**
Delete Successfully
Delete Error
- Error deleting hospital with associated patients
- Error deleting hospital with invalid ID
**Location Pin**
Delete Successfully
Delete Error
- Invalid ID
**Patient**
Delete Successfully
Delete Error
- Invalid ID
**User**
Delete …
> Update all delete mutations to return entity id

- migrations/20200927132044-update-patient-barcode-non-nullable.js
- schema/patient.js
[Notion ticket](https://www.notion.so/uwblueprintexecs/no-duplicate-barcodes-d0cd44a9ce9e4812bb250011edad50f7)
- Added migration to:
- Update existing null barcode values to be the patient ID
- Update `barcodeValue` column in patient table to have a `NOT NULL` constraint
- Note that on `down` method, removing the constraint must occur first in order to reverse to null barcode values
- Updated GraphQL schema for patient by adding `!` to make `barcodeValue` non-nullable
In `~/paramedics-shared/paramedics-web`, open two terminals
- To execute a bash shell on the container, run `pmc-s`
- To access the db, run `pmc-db`
- Prior to running migration, create a patient with no barcode value (null) and check DB to ensure patient exists
- Check the migration status with `sequelize db:migrate:status` …
> No duplicate patient barcodes

- seeders/20200717011432-locationPins.js
[Notion ticket](https://www.notion.so/uwblueprintexecs/396370c5e09f4c28bc7f455a7e84c908?v=3751aa62a2594c74b7e0ecb363304c24&p=419c95b8cc0d4a8ab4b2783744dfb16c)
- Updated pin latitudes and longitudes so that it is centred in the Waterloo region
- Created own event and user for location pin seeder
- Make sure that you can seed and un-seed the database without any problems
- Check the database itself and make sure `locationPins` has the information laid out in the seeder
before opening PR
filling out PR
after opening PR
> Updating location pins

- migrations/20200923012433-setup-roles.js
- models/role.js
- resolvers/ambulance.js
- resolvers/collectionPoint.js
- resolvers/event.js
- resolvers/hospital.js
- resolvers/locationPin.js
- resolvers/patient.js
- resolvers/user.js
- utils/enum.js
- utils/validators.js
[Notion ticket](https://www.notion.so/uwblueprintexecs/Backend-Authorization-0f29dae7aad449e98ab43ee1e7f28316)
- Added role validators to:
Ambulances,
Collection Points,
Events,
Hospitals,
Location Pins,
Patients,
Users,
- Added the implementation of the role validator to `validator.js`
- Added demoRole for testing
-  Added enumerations for roles:
COMMANDER,
SUPERVISOR,
DISPATCH,
- Test by changing the role in`demoRole` in `validator.js`
- Check each resolver through GraphQL to see if it catches roles that do not have sufficient permissions
- Check that each resolver worked if the demo role had sufficient permission 
- Made sure the role argument for each resolver matches the spreadsheet permissions
While testing, please consult [this](https://docs.google.com/spreadsheets/d/1JTQlflqYCW8p78 …
> Added role validators to resolvers

- migrations/20201116042500-update-ambulances-unique.js
- migrations/20201116042508-update-hospitals-unique.js
[Notion ticket](https://www.notion.so/uwblueprintexecs/no-duplicate-resources-8713dd5852f04c0eb67558cf562da051)
Associated frontend PR: https://github.com/uwblueprint/paramedics-react/pull/58
- `migrations/20201116042500-update-ambulances-unique.js`
- Remove all duplicate ambulances
- Add UNIQUE constraint on `vehicleNumber` column of ambulance table
- `migrations/20201116042508-update-hospitals-unique.js`
- Remove all duplicate hospitals
- Add UNIQUE constraint on `name` column of hospital table
- Create duplicate ambulances and hospitals
- Run migrations
- Check DB to ensure that duplicates no longer exist
- Try creating duplicate ambulances and hospitals again - this should not be possible
- Undo migrations and try creating duplicate ambulances and hospitals - this should be possible …
> Update hospitals and ambulances to be UNIQUE

- resolvers/locationPin.js
- Just added a return statement so that we actually return the ID of a deleted pin
- Just make sure you don't run into any nullable errors in the GraphQL console
before opening PR
filling out PR
after opening PR
> Adding return to deleteLocationPin resolver

- app.js
- migrations/20201211042230-load-akshay-user.js
- resolvers/patient.js
- server.js
- strategies/bp_saml_auth0.js
- adding support for multiple SAML strategies on passport via dependency injection
- functionally the same changes as #81
> Support multiple SAML strategies

- resolvers/locationPin.js
- Renamed fields in `addLocationPin` and `editLocationPin` to `ccpId` for consistency
- Make sure that adding and editing pins works (make sure to query the `ccpId` field)
before opening PR
filling out PR
after opening PR
> Renaming ccpParentId
